name: Haskell CI

on: [push]

jobs:
  build-deps:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Cache ~/.stack
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.stack
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-global-${{ hashFiles('stack.yaml.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-master-stack-global

    - name: Cache ~/.cabal
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.cabal
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-cabal-${{ hashFiles('stack.yaml.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-master-cabal

    - name: Cache ~/.ghc
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.ghc
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-ghc-${{ hashFiles('stack.yaml.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-master-ghc

    - name: Cache .stack-work
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: .stack-work
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-work-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{runner.os}}-master-stack-work

    - uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
        enable-stack: true
        stack-version: '2.5.1'

    - name: Install dependencies
      run: |
        pwd
        ls
        stack --no-terminal build --test --no-run-tests --only-dependencies

  build:
    needs:
    - build-deps
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Cache ~/.stack
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.stack
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-global-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-global-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-stack-global

    - name: Cache ~/.cabal
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.cabal
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-cabal-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-cabal-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-cabal

    - name: Cache ~/.ghc
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.ghc
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-ghc-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-ghc-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-ghc

    - name: Cache .stack-work
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: .stack-work
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-work-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-work-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-stack-work
    - uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
        enable-stack: true
        stack-version: '2.5.1'
    - name: Build
      run: |
        stack --no-terminal build --test --no-run-tests

  test:
    needs:
    - build-deps
    - build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Cache ~/.stack
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.stack
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-global-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-global-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-stack-global

    - name: Cache ~/.cabal
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.cabal
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-cabal-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-cabal-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-cabal

    - name: Cache ~/.ghc
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: ~/.ghc
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-ghc-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-ghc-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-ghc

    - name: Cache .stack-work
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: .stack-work
        # An explicit key for restoring and saving the cache
        key: ${{runner.os}}-${{github.ref}}-stack-work-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{runner.os}}-${{github.ref}}-stack-work-${{ hashFiles('stack.yaml.lock') }}
          ${{runner.os}}-master-stack-work
    - uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
        enable-stack: true
        stack-version: '2.5.1'

    - name: Run tests
      run: stack --no-terminal build --test
